### ISSUE TITLE
About code gen in spark sql

### ISSUE THREAD

**Issue by bithw1** [bartosz25/spark-scala-playground#12]
Hi @bartosz25 

I am reading your post https://www.waitingforcode.com/apache-spark-sql/generated-code-spark-sql/read,

I would ask whether you'd like write something about the `internal working` of spark sql code generation, 
1. for the basic code generation(GenerateProjection, GenerateFiltering, GenerateOrdering), how are the mutable state variables of CodegenContext is used.

2. How WholeStageCodeGeneration works

**Comment by bartosz25** [comment]
Hi @bithw1 ,

Sure, it's a good idea. Especially that the post you quote became pretty old and deserves some refresh :) I think I should be able to publish it by the end of the year or in the 2 first weeks of January 2019. 

Next 2 weeks I will focus on the GraphX (just published a small survey of distributed graph processing frameworks https://www.waitingforcode.com/graphs/graph-processing-frameworks-survey/read)  and on the new features of Spark 2.4.0. Also I'll publish soon the posts about off-heap memory and multiple contexts in Apache Spark which are related to your previous questions.

Please let the issue open. I'll maybe ask you some specific questions about what you would like to see in the post. 

Best regards,
Bartosz.

**Comment by bithw1** [comment]
Sure, thank you very much, @bartosz25, it is very kind of you.

**Comment by bartosz25** [comment]
Hi @bithw1 

I published a new post about the code generation in Apache Spark. I hope it'll answer at least a part your questions.

Best regards,
Bartosz.

**Comment by bithw1** [comment]
Thanks @bartosz25 !, it helps a lot.
