### ISSUE TITLE
Kafka test case code

### ISSUE THREAD

**Issue by bithw1** [bartosz25/spark-scala-playground#2]
Hi @bartosz25 
I reading your Kafka articles at http://www.waitingforcode.com/apache-kafka. They are very helpful, but I didn't find the test case code in your github repo, could you please point it to me? Thank you very much

**Comment by bartosz25** [comment]
Hi, you can find it in this repo: https://github.com/bartosz25/bigdata-sandbox

**Comment by bithw1** [comment]
That's perfect, I found it. Thanks @bartosz25, both for the articles and the test cases!
